apiVersion: apps/v1
kind: Job
metadata:
  name: kimo-cloudstorage-deployment
  namespace: wl-identity-namespace
spec:
  replicas: 
  selector:
    matchLabels:
      app: kimo-sbucket
  template:
    metadata:
      labels:
        app: kimo-sbucket
    spec:
      containers:
        - name: kimo-py-container
           image: gcr.io/sandbox-io-289003/kimo-py-app
         resartPolicy: Never        
          ports:
            - containerPort: 8080
      serviceAccountName: kube-sa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
